project:
  type: website
  output-dir: "docs"

website:
  title: "Hasan"
  twitter-card: true
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: resume.qmd
        text: Resume
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "© 2024 Md Hasan"

format:
  html:
    # theme: flatly
    light: Lux
    dark: [Lux, theme-dark.scss]
    css: styles.css
    fontsize: 1.2em
    linestretch: 1.7
    toc: false
    # dark: darkly
editor: visual

