project:
  type: website

website:
  title: "Hasan"
  twitter-card: true
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact
      - href: resume.qmd
        text: Resume

  page-footer:
    left: "© 2021 Md Hasan"
format:
  html:
    # theme: flatly
    light: Lux
    dark: [Lux, theme-dark.scss]
    css: styles.css
    fontsize: 1.2em
    linestretch: 1.7
    toc: false
    # dark: darkly

editor: visual

