project:
  type: website
  output-dir: "docs"

website:
  title: "Hasan"
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    creator: "@mdhasanai"
    site: "@mdhasanai"
    card-style: summary_large_image
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      # - href: resume.qmd
      #   text: Resume
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "© 2024 Md Hasan"

format:
  html:
    theme: 
      light: [darkly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    fontsize: 1.2em
    linestretch: 1.7
    toc: false
editor: visual

