name: Deploy to GitHub Pages

# Trigger this workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the job that will build and deploy the site
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Quarto
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    # Step 3: Render the site with Quarto
    - name: Render the site
      run: quarto render

    # Step 4: Deploy the site to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs  # This should match the output directory from your _quarto.yml
